[2024-02-22T08:40:30.942+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_s3_bucket.download_from_s3 manual__2024-02-22T08:38:03.419463+00:00 [queued]>
[2024-02-22T08:40:30.949+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_s3_bucket.download_from_s3 manual__2024-02-22T08:38:03.419463+00:00 [queued]>
[2024-02-22T08:40:30.949+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2024-02-22T08:40:30.957+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_from_s3> on 2024-02-22 08:38:03.419463+00:00
[2024-02-22T08:40:30.961+0000] {standard_task_runner.py:57} INFO - Started process 2390 to run task
[2024-02-22T08:40:30.963+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_s3_bucket', 'download_from_s3', 'manual__2024-02-22T08:38:03.419463+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/simples3bucketpipeline.py', '--cfg-path', '/tmp/tmpilzd3ajj']
[2024-02-22T08:40:30.965+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask download_from_s3
[2024-02-22T08:40:30.995+0000] {task_command.py:416} INFO - Running <TaskInstance: test_s3_bucket.download_from_s3 manual__2024-02-22T08:38:03.419463+00:00 [running]> on host f659216eeba3
[2024-02-22T08:40:31.046+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Vishwaranjan' AIRFLOW_CTX_DAG_ID='test_s3_bucket' AIRFLOW_CTX_TASK_ID='download_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T08:38:03.419463+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T08:38:03.419463+00:00'
[2024-02-22T08:40:31.047+0000] {s3.py:1366} INFO - This function shadows the 'download_file' method of S3 API, but it is not the same. If you want to use the original method from S3 API, please call 'S3Hook.get_conn().download_file()'
[2024-02-22T08:40:31.047+0000] {s3.py:1372} INFO - Downloading source S3 file from Bucket testbucket-3908 with path IPL_players.csv
[2024-02-22T08:40:31.053+0000] {base.py:73} INFO - Using connection ID 's3-conn' for task execution.
[2024-02-22T08:40:31.054+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3-conn', conn_type='aws') credentials retrieved from login and password.
[2024-02-22T08:40:34.412+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simples3bucketpipeline.py", line 22, in download_from_s3
    hook.download_file(key=key,bucket_name=bucket_name,local_path=local_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1398, in download_file
    file = NamedTemporaryFile(dir=local_path, prefix="airflow_tmp_", delete=False)  # type: ignore
  File "/usr/local/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/files/s3/airflow_tmp_b0tpvuj4'
[2024-02-22T08:40:34.429+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_s3_bucket, task_id=download_from_s3, execution_date=20240222T083803, start_date=20240222T084030, end_date=20240222T084034
[2024-02-22T08:40:34.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task download_from_s3 ([Errno 2] No such file or directory: '/opt/airflow/files/s3/airflow_tmp_b0tpvuj4'; 2390)
[2024-02-22T08:40:34.494+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-22T08:40:34.508+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
